package com.example.data

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Data-layer coverage for category management.
 *
 * A real gap was found during manual testing: adding a category with a name that already
 * exists was silently allowed. The fix lives in [CategoryManagementTab]'s "+" button handler,
 * which now rejects a duplicate (case-insensitive) name with an inline error message before
 * ever calling [com.example.ui.viewmodel.FinanceViewModel.addCategory] - see
 * CategoryManagementTab.kt's `isDuplicate` check. That's a deliberate choice to validate at the
 * UI layer rather than adding a DB constraint: [CategoryDao] itself intentionally still allows
 * two rows with the same name (`duplicateCategoryNames_areBothPersisted_knownGap` below pins
 * that down), since the DAO has no visibility into "is this a duplicate the user should be
 * warned about" vs. legitimate data from elsewhere. If a future change adds a DB-level
 * constraint instead, update this test to match rather than treating it as a break.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class CategoryDaoTest {

    private lateinit var db: AppDatabase
    private lateinit var categoryDao: CategoryDao

    @Before
    fun setUp() {
        db = Room.inMemoryDatabaseBuilder(
            ApplicationProvider.getApplicationContext(),
            AppDatabase::class.java
        ).allowMainThreadQueries().build()
        categoryDao = db.categoryDao()
    }

    @After
    fun tearDown() {
        db.close()
    }

    @Test
    fun insertCategory_appearsInGetAllCategories() = runTest {
        categoryDao.insertCategory(Category(name = "Groceries", iconName = "ic_default"))

        val all = categoryDao.getAllCategories().first()

        assertEquals(1, all.size)
        assertEquals("Groceries", all.first().name)
    }

    @Test
    fun duplicateCategoryNames_areBothPersisted_knownGap() = runTest {
        // Mirrors what CategoryManagementTab's "+" button does: it only checks the input
        // isn't blank, never whether the name is already taken.
        categoryDao.insertCategory(Category(name = "Test Category"))
        categoryDao.insertCategory(Category(name = "Test Category"))

        val all = categoryDao.getAllCategories().first()
        val matching = all.filter { it.name == "Test Category" }

        // Documents current behavior: two distinct rows (different autogenerated ids), same
        // name. If this ever drops to 1, someone added de-duplication - update this test
        // rather than treating the change as a break.
        assertEquals(2, matching.size)
        assertTrue(matching[0].id != matching[1].id)
    }

    @Test
    fun deleteCategory_removesOnlyTheMatchingRow() = runTest {
        categoryDao.insertCategory(Category(name = "Food"))
        categoryDao.insertCategory(Category(name = "Shopping"))
        val toDelete = categoryDao.getAllCategories().first().first { it.name == "Food" }

        categoryDao.deleteCategory(toDelete)

        val remaining = categoryDao.getAllCategories().first()
        assertEquals(1, remaining.size)
        assertEquals("Shopping", remaining.first().name)
    }
}
